name: Documentation

on:
  push:
    branches: 
      - documentation
  pull_request:
    branches: 
      - documentation

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Verify directory structure
      - name: List directory structure
        run: |
          ls -la
          ls -la website/

      # Generate SVG files using PlantUML
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        timeout-minutes: 3
        run: |
          cd website
          npm run ci

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: ${{ github.actor }}
          user_email: ${{ github.event.pusher.email || github.actor }}

      # https://github.com/marketplace/actions/create-an-issue
      - name: Create issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/DOCUMENTATION_ISSUE_TEMPLATE.md
