name: PlantUML to SVG
on:
  push:
    paths:
      - '**.puml'
  pull_request:
    paths:
      - '**.puml'

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg docs/**/*.puml

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/**/*.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatically convert PlantUML to SVG" && git push) 